config/routes.rb
Fromthepage::Application.routes.draw do
  # TODO: make the URL fall under user and collection profile
  scope ':user_slug' do
    scope ':collection_id' do
      mount Thredded::Engine => '/forum'
    end
  end

  namespace :emldict do
    get '/', to: 'base#index'
    resource :source
    resources :parsed, only: %i[index show], param: :collection_slug do
      get ':work_slug', to: 'parsed#work_show', as: :work_show
      get ':work_slug/export', to: 'parsed#work_export', as: :work_export
      get ':work_slug/needs-review', to: 'parsed#work_needs_review_show', as: :work_needs_review_show
    end
  end

  root to: 'static#landing_page'
  get '/blog' => redirect('https://fromthepage.com/blog/')

  devise_for :users,
             controllers: { masquerades: 'masquerades', registrations: 'registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'users/new_trial' => 'registrations#new_trial'
    get ':user_slug/sign_up', to: 'registrations#owner_new', as: 'new_for_owner'
    post 'registrations/choose_provider', to: 'registrations#choose_saml'
    post 'registrations/set_provider', to: 'registrations#set_saml'
    match '/users/auth/saml/:identity_provider_id/callback',
          via: %i[get post],
          to: 'users/omniauth_callbacks#saml',
          as: 'user_omniauth_callback'

    match '/users/auth/saml/:identity_provider_id',
          via: %i[get post],
          to: 'users/omniauth_callbacks#passthru',
          as: 'user_omniauth_authorize'
  end

  iiif_for 'riiif/image', at: '/image-service'

  resources :notes

  scope 'admin', as: 'admin' do
    get '/' => 'admin#index'
    get 'collection_list', to: 'admin#collection_list'
    get 'work_list', to: 'admin#work_list'
    get 'owner_list', to: 'admin#owner_list'
    get 'user_list', to: 'admin#user_list'
    get 'flag_list', to: 'admin#flag_list'
    get 'moderation', to: 'admin#moderation'
    get 'uploads', to: 'admin#uploads'
    get 'tail_logfile', to: 'admin#tail_logfile'
    get 'settings', to: 'admin#settings'
    get 'user_visits', to: 'admin#user_visits'
    get 'edit_user', to: 'admin#edit_user'
    get 'autoflag', to: 'admin#autoflag'
    get 'ok_flag', to: 'admin#ok_flag'
    get 'revert_flag', to: 'admin#revert_flag'
    get 'delete_user', to: 'admin#delete_user'
    get 'view_processing_log', to: 'admin#view_processing_log'
    get 'delete_upload', to: 'admin#delete_upload'
    get 'visit_deeds', to: 'admin#visit_deeds'
    get 'visit_actions', to: 'admin#visit_actions'
    get 'expunge_confirmation', to: 'admin#expunge_confirmation'
    get 'ok_user', to: 'admin#ok_user'
    get 'downgrade', to: 'admin#downgrade'
    post 'update', to: 'admin#update'
    patch 'update_user', to: 'admin#update_user'
    patch 'expunge_user', to: 'admin#expunge_user'
  end

  scope 'facets', as: 'facets' do
    get 'enable', to: 'facets#enable'
    get 'disable', to: 'facets#disable'
    post 'update', to: 'facets#update'
    get ':collection_id/localize', to: 'facets#localize', as: 'localize'
    post 'update_localization', to: 'facets#update_localization'
  end

  scope 'collection', as: 'collection' do
    get 'new', to: 'collection#new'
    get 'delete', to: 'collection#delete'
    get 'activity_download', to: 'collection#activity_download'
    get 'show', to: 'collection#show', as: 'show'
    get 'toggle_collection_active', to: 'collection#toggle_collection_active'
    get 'toggle_collection_api_access', to: 'collection#toggle_collection_api_access'
    get 'contributors_download', to: 'collection#contributors_download'
    get 'enable_fields', to: 'collection#enable_fields'
    get 'enable_metadata_entry', to: 'collection#enable_metadata_entry'
    get 'enable_document_sets', to: 'collection#enable_document_sets'
    get 'enable_messageboards', to: 'collection#enable_messageboards'
    get 'enable_ocr', to: 'collection#enable_ocr'
    get 'disable_ocr', to: 'collection#disable_ocr'
    get 'blank_collection', to: 'collection#blank_collection'
    get 'edit', to: 'collection#edit'
    get ':collection_id/edit_owners', to: 'collection#edit_owners', as: 'edit_owners'
    post 'add_reviewer', to: 'collection#add_reviewer'
    get ':collection_id/edit_reviewers', to: 'collection#edit_reviewers', as: 'edit_reviewers'
    post 'remove_reviewer', to: 'collection#remove_reviewer'
    get 'disable_document_sets', to: 'collection#disable_document_sets'
    get 'disable_messageboards', to: 'collection#disable_messageboards'
    get 'disable_fields', to: 'collection#disable_fields'
    get 'disable_metadata_entry', to: 'collection#disable_metadata_entry'
    get 'publish_collection', to: 'collection#publish_collection'
    get ':collection_id/edit_collaborators', to: 'collection#edit_collaborators', as: 'edit_collaborators'
    get 'restrict_collection', to: 'collection#restrict_collection'
    get 'restrict_transcreibed', to: 'collection#restrict_transcribed'
    post 'add_collaborator', to: 'collection#add_collaborator'
    post 'remove_collaborator', to: 'collection#remove_collaborator'
    post 'add_owner', to: 'collection#add_owner'
    post 'remove_owner', to: 'collection#remove_owner'
    post 'create', to: 'collection#create'
    get ':collection_id/search_users', to: 'collection#search_users', as: 'search_users'
    match 'update/:id', to: 'collection#update', via: %i[get post], as: 'update'

    scope 'metadata', as: 'metadata' do
      get ':id/example', to: 'metadata#example', as: :example
      get ':id/upload', to: 'metadata#upload', as: :upload
      get 'csv_error', to: 'metadata#csv_error'
      post 'create', to: 'metadata#create'
    end

    scope 'editor_button', as: 'editor_button' do
      get ':collection_id/edit', to: 'collection#edit_buttons', as: 'edit'
      post ':collection_id/edit', to: 'collection#update_buttons', as: 'update'
    end
  end

  scope 'work', as: 'work' do
    get 'delete', to: 'work#delete'
    get 'update_featured_page', to: 'work#update_featured_page'
    get 'pages_tab', to: 'work#pages_tab'
    get 'edit', to: 'work#edit'
    get 'revert', to: 'work#revert'
    post 'update', to: 'work#update'
    post 'create', to: 'work#create'
    patch 'update_work', to: 'work#update_work'
  end

  scope 'page', as: 'page' do
    get 'new', to: 'page#new'
    get 'delete', to: 'page#delete'
    get 'reorder_page', to: 'page#reorder_page'
    get 'edit', to: 'page#edit'
    get 'rotate', to: 'page#rotate'
    post 'update', to: 'page#update'
    post 'create', to: 'page#create'
  end

  scope 'article', as: 'article' do
    get 'list', to: 'article#list'
    get 'tooltip', to: 'article#tooltip'
    get 'delete', to: 'article#delete'
    get 'show', to: 'article#show'
    post 'combine_duplicate', to: 'article#combine_duplicate'
    post 'article_category', to: 'article#article_category'
  end

  scope 'export', as: 'export' do
    get '/', to: 'export#index'
    get 'export_work', to: 'export#export_work'
    get 'export_all_works', to: 'export#export_all_works'
    post ':collection_id/:work_id/printable', to: 'export#printable', as: 'printable'
    get 'show', to: 'export#show'
    get ':work_id/tei', to: 'export#tei', as: 'tei'
    get 'subject_csv', to: 'export#subject_index_csv'
    get 'subject_details_csv', to: 'export#subject_details_csv'
    get 'subject_coocurrence_csv', to: 'export#subject_coocurrence_csv'
    get 'table_csv', to: 'export#table_csv'
    get 'export_all_tables', to: 'export#export_all_tables'
    get ':collection_id/work_metadata_csv', to: 'export#work_metadata_csv', as: 'work_metadata'
    get 'edit_contentdm_credentials', to: 'export#edit_contentdm_credentials'
    post 'update_contentdm_credentials', to: 'export#update_contentdm_credentials'
    get 'work_plaintext_verbatim', to: 'export#work_plaintext_verbatim'
  end

  scope 'bulk_export', as: 'bulk_export' do
    get ':collection_id/new', to: 'bulk_export#new', as: 'new'
    post ':collection_id/new', to: 'bulk_export#create', as: 'create'
    post ':collection_id/work_create', to: 'bulk_export#create_for_work', as: 'create_for_work'
    get '/', to: 'bulk_export#index', as: 'index'
    get ':bulk_export_id', to: 'bulk_export#show', as: 'show'
    get ':bulk_export_id/download', to: 'bulk_export#download', as: 'download'
  end

  scope 'ia', as: 'ia' do
    get 'import_work', to: 'ia#import_work'
    get 'book_form', to: 'ia#ia_book_form'
    get 'manage', to: 'ia#manage'
    get 'mark_beginning', to: 'ia#mark_beginning'
    get 'mark_end', to: 'ia#mark_end'
    get 'title_from_ocr_top', to: 'ia#title_from_ocr_top'
    get 'title_from_ocr_bottom', to: 'ia#title_from_ocr_bottom'
    post 'convert', to: 'ia#convert'
    post 'import_work', to: 'ia#import_work'
    match 'confirm_import', to: 'ia#confirm_import', via: %i[get post]
  end

  scope 'dashboard', as: 'dashboard' do
    get '/' => 'dashboard#index'
    get 'owner' => 'dashboard#owner'
    get 'watchlist' => 'dashboard#watchlist'
    get 'startproject', to: 'dashboard#startproject'
    get 'summary', to: 'dashboard#summary'
    get 'exports', to: 'dashboard#exports'
    get 'collaborator_time_export', to: 'dashboard#collaborator_time_export'
    post 'new_upload', to: 'dashboard#new_upload'
    post 'create_work', to: 'dashboard#create_work'
  end

  scope 'category', as: 'category' do
    get 'edit', to: 'category#edit'
    get 'add_new', to: 'category#add_new'
    get 'enable_gis', to: 'category#enable_gis'
    get 'disable_gis', to: 'category#disable_gis'
    get 'delete', to: 'category#delete'
    post 'create', to: 'category#create'
    patch 'update', to: 'category#update'
  end

  scope 'transcribe', as: 'transcribe' do
    get 'mark_page_blank', to: 'transcribe#mark_page_blank'
    get 'display_page', to: 'transcribe#display_page'
    get 'assign_categories', to: 'transcribe#assign_categories'
    get 'guest', to: 'transcribe#guest'
    get 'edit_fields', to: 'transcribe#edit_fields'

app/models/note.rb
class Note < ApplicationRecord
  # Notes are comments on pages.  In the future they may
  # be comments on works, comments on image fragments,
  # comments on articles, or questions and answers

  # automated stuff
  acts_as_tree

  # associations
  belongs_to :user, optional: true
  belongs_to :page, optional: true
  belongs_to :work, optional: true
  belongs_to :collection, optional: true
  has_one :deed, :dependent => :destroy
  has_many :flags

  after_save :email_users
  after_save :update_page_last_note

  validates :body, presence: true

  scope :active, -> { joins(:user).where(users: {deleted: false}) }

  after_create :check_content

  def check_content
    Flag.check_note(self)
  end

  def email_users
    if SMTP_ENABLED
      previous_users = User.joins(:notes).where(notes: {id: self.page.notes.ids}).joins(:notification).where(notifications: {note_added: true}).distinct
      previous_users.each do |user|
        #send email regarding previous note, if it isn't the same user
        if (user.id != self.user_id && self.work.access_object(user))
          begin
            UserMailer.added_note(user, self).deliver!
          rescue StandardError => e
            print "SMTP Failed: Exception: #{e.message}"
          end
        end
      end
    end
  end

  def update_page_last_note
    self.page.update_column(:last_note_updated_at, page.notes.last.updated_at) if self.page
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include ActionView::Helpers::TextHelper
  PAGES_PER_SCREEN = 20

  def create
    @note = Note.new(note_params)
    # truncate the body for the title
    @note.title = @note.body
    @note.title = truncate(@note.title, length: 250, escape: false)
    # add param-loaded associations
    @note.page = @page
    @note.work = @work
    @note.collection = @work.collection
    @note.user = current_user

    respond_to do |format|
      if not user_signed_in?
        format.html { redirect_back fallback_location: root_path, flash: { error: t('.must_be_logged') } }
      elsif @note.save
        record_deed
        format.json { render json: { html: render_to_string(partial: 'note.html', locals: { note: @note }, formats: [:html]) }, status: :created }
        format.html { redirect_back fallback_location: @note, notice: t('.note_has_been_created') }
      else
        format.json { render json: @note.errors.full_messages, status: :unprocessable_entity }
        format.html { redirect_back fallback_location: @note, flash: { error: t('.error_creating_note') } }
      end
    end
  end

  def update
    @note = Note.find(params[:id])
    respond_to do |format|
      if @note.update(note_params)
        note_body = sanitize(@note.body, tags: %w(strong b em i a), attributes: %w(href))

        format.json { render json: { html: simple_format(note_body) }, status: :ok }
        format.html { redirect_back fallback_location: @note, notice: t('.note_has_been_updated') }
      else
        format.json { render json: @note.errors.full_messages, status: :unprocessable_entity }
        format.html { redirect_back fallback_location: @note, flash: { error: t('.error_updating_note') } }
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.deed.delete
    @note.delete
    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_back fallback_location: root_path, notice: t('.note_has_been_deleted') }
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def show
    @note = Note.find(params[:id])
  end

  def record_deed
    deed = Deed.new
    deed.note = @note
    deed.page = @page
    deed.work = @work
    deed.collection = @work.collection
    deed.deed_type = DeedType::NOTE_ADDED
    deed.user = current_user

    deed.save!
  end

  def discussions
    @pages = @collection.pages.where.not(last_note_updated_at: nil).reorder(last_note_updated_at: :desc).paginate :page => params[:page], :per_page => PAGES_PER_SCREEN
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end
end

app/views/notes/_note.html.slim
.user-bubble.editable(id="note-#{note.id}")
  =link_to(user_profile_path(:user_id => note.user.id))
    =profile_picture(note.user)
  .user-bubble_content
    -if note.user == current_user
      .user-bubble_actions
        a(data-note-edit=note.id title=t('.edit'))
          =svg_symbol '#icon-edit', class: 'icon'
        =link_to(note, method: :delete, remote: true, data: { "note-delete" => note.id, :confirm => t('.confirm_delete_message') }, title: t('.delete'))
          =svg_symbol '#icon-remove-sign', class: 'icon', title: t('.delete')
    -elsif current_user && current_user.like_owner?(@work)
      .user-bubble_actions
        =link_to(note, method: :delete, remote: true, data: { "note-delete" => note.id, :confirm => t('.confirm_delete_message') }, title: t('.delete'))
          =svg_symbol '#icon-remove-sign', class: 'icon', title: t('.delete')
    =time_tag note.created_at
      =link_to note.user.display_name, user_profile_path(:user_id => note.user.id)
      |&nbsp;
      =t('time_ago_in_words', time: time_ago_in_words(note.created_at))
    .user-bubble_note ==simple_format(sanitize(note.body, tags: %w(strong b em i a), attributes: %w(href)))

  -if note.user == current_user
    =form_for note, remote: true, :html => { class: 'user-bubble_form' } do |f|
      .user-bubble_form_editor
        =f.text_area :body, :rows => 4
      .user-bubble_form_footer
        span.user-bubble_form_error
        -if @collection.voice_recognition
          span.voice-info.voice
          =image_submit_tag 'mic-icon.png', height: '40', alt: t('.microphone'), class: 'voice', id: 'start_img_update', onclick: 'startButton(event);'
        a(data-note-edit=note.id title=t('.edit')) #{t('.cancel')}
        =f.button t('.update')

app/views/notes/_notes.html.slim
-if @page
  -notes = @page.notes
-else
  -notes = @work.notes.where(page_id: nil)
-if notes.empty?
  p.acenter.fglight(data-note-empty)
    = t('.nobody_has_written_a_note')
-unless user_signed_in?
  p.acenter.fglight = t('.please_sign_in_to_write', link: link_to(t('.sign_in'), new_user_session_path)).html_safe

-notes.each do |note|
  =render({ partial: 'notes/note', locals: { note: note }})

-if user_signed_in?
  .user-bubble
    =profile_picture(current_user)

    =form_for :note, url: notes_path, remote: true, html: { class: 'user-bubble_form' } do |f|
      -if @page
        =hidden_field_tag(:page_id, @page.id)
      -else
        =hidden_field_tag(:work_id, @work.id)

      =hidden_field_tag(:collection_id, @collection.slug)
      .user-bubble_form_editor
        =f.text_area :body, :rows => 4, :placeholder => t('.write_a_new_note')
      .user-bubble_form_footer
        span.user-bubble_form_error
        =f.label :body, t('.note_body'), class: 'hidden'
        -if @collection.voice_recognition
          span.voice-info.voice
          =image_submit_tag 'mic-icon.png', height: '40', alt: t('.microphone'), class: 'voice', id: 'start_img_note', onclick: 'startButton(event);'
        =f.button t('.save_note'), id: 'save_note_button'

  -content_for :javascript
    javascript:
      $(function() {
        // Toggle note edit
        $(document).on('click', '[data-note-edit]', function() {
          var $container = $(this).closest('.user-bubble').toggleClass('edit');
          if($container.hasClass('edit')) {
            $('form', $container)[0].reset();
            $('.user-bubble_form_error', $container).empty();
          }
        });

        // Create and update note
        $(document).on('ajax:complete', 'form.user-bubble_form', function(e, xhr) {
          var $container = $(this).parent();
          var $error = $('.user-bubble_form_error', $container).empty();

          if (e.response === undefined && xhr.responseText.includes("Sign In")) {
            var message = "You need to be logged in to create this note."
            $error.text('Error: ' + message);
            return false;
          }

          if(xhr.status === 201) {
            // Note created
            var content = xhr.responseJSON.html;
            $(content).hide().insertBefore($container).fadeIn();
            $('[data-note-empty]').hide();
            this.reset();
          } else if(xhr.status === 200) {
            // Note updated
            this.reset();
            var content = xhr.responseJSON.html;
            $container.removeClass('edit');
            $('.user-bubble_note', $container).html(content);
          } else if(xhr.status === 500) {
            var message = xhr.statusText;
            $error.text('Error: ' + message);
          } else {
            // Error occurred
            var message = xhr.responseJSON.join('. ');
            $error.text('Error: ' + message);
          }
        });

        // Delete note
        $(document).on('ajax:complete', '[data-note-delete]', function(e, xhr) {
          if(xhr.status === 200 || xhr.status === 204) {
            var $container = $(this).closest('.user-bubble');
            $container.fadeOut(function() { $(this).remove(); });
          }
        });


      });

app/views/notes/discussions.html.slim
=render({ :partial => '/shared/collection_tabs', :locals => { :selected => 14, :collection_id => @collection.id }})

.thredded--main-container

	=render('thredded/shared/breadcrumbs')

	-@pages.each do |page|
		-note=page.notes.last
		.work-page 
			.work-page_thumbnail
			  -if page.ia_leaf
			    =link_to(image_tag(page.ia_leaf.thumb_url, alt: page.title), collection_forum_page_path(@collection.owner, @collection, page.work, page.id, anchor: "notes") )
			  -elsif page.sc_canvas
			    =link_to(image_tag(page.sc_canvas.thumbnail_url, alt: page.title), collection_forum_page_path(@collection.owner, @collection, page.work, page.id, anchor: "notes"))
			  -else
			    =link_to image_tag(file_to_url(page.thumbnail_image), alt: page.title), collection_forum_page_path(@collection.owner, @collection, page.work, page.id, anchor: "notes")
	    .work-page_content
	    	h4.work-page_title 
	    		=link_to page.title, collection_forum_page_path(@collection.owner, @collection, page.work, page.id, anchor: "notes") 
	    		span &nbsp; in #{page.work.title}
	    	=t(".most_recent_of") 
	    	=link_to t(".total_notes", count: page.notes.count), collection_forum_page_path(@collection.owner, @collection, page.work, page.id, anchor: "notes")
			.user-bubble.editable.comment-bubble(id="note-#{note.id}")
	  		=link_to(user_profile_path(:user_id => note.user.id))
	    		=profile_picture(note.user)
	  		.user-bubble_content
			    =time_tag note.created_at
			      =link_to note.user.display_name, user_profile_path(:user_id => note.user.id)
			      |&nbsp;
			      =t('time_ago_in_words', time: time_ago_in_words(note.created_at))
			    .user-bubble_note ==simple_format(sanitize(note.body, tags: %w(strong b em i a), attributes: %w(href)))
	=render(:partial => 'shared/pagination', :locals => { :model => @pages, :entries_info => true })