config/routes.rb
Fromthepage::Application.routes.draw do
  # TODO: make the URL fall under user and collection profile
  scope ':user_slug' do
    scope ':collection_id' do
      mount Thredded::Engine => '/forum'
    end
  end

  namespace :emldict do
    get '/', to: 'base#index'
    resource :source
    resources :parsed, only: %i[index show], param: :collection_slug do
      get ':work_slug', to: 'parsed#work_show', as: :work_show
      get ':work_slug/export', to: 'parsed#work_export', as: :work_export
      get ':work_slug/needs-review', to: 'parsed#work_needs_review_show', as: :work_needs_review_show
    end
  end

  root to: 'static#landing_page'
  get '/blog' => redirect('https://fromthepage.com/blog/')

  devise_for :users,
             controllers: { masquerades: 'masquerades', registrations: 'registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'users/new_trial' => 'registrations#new_trial'
    get ':user_slug/sign_up', to: 'registrations#owner_new', as: 'new_for_owner'
    post 'registrations/choose_provider', to: 'registrations#choose_saml'
    post 'registrations/set_provider', to: 'registrations#set_saml'
    match '/users/auth/saml/:identity_provider_id/callback',
          via: %i[get post],
          to: 'users/omniauth_callbacks#saml',
          as: 'user_omniauth_callback'

    match '/users/auth/saml/:identity_provider_id',
          via: %i[get post],
          to: 'users/omniauth_callbacks#passthru',
          as: 'user_omniauth_authorize'
  end

  iiif_for 'riiif/image', at: '/image-service'

  resources :notes

  scope 'admin', as: 'admin' do
    get '/' => 'admin#index'
    get 'collection_list', to: 'admin#collection_list'
    get 'work_list', to: 'admin#work_list'
    get 'owner_list', to: 'admin#owner_list'
    get 'user_list', to: 'admin#user_list'
    get 'flag_list', to: 'admin#flag_list'
    get 'moderation', to: 'admin#moderation'
    get 'uploads', to: 'admin#uploads'
    get 'tail_logfile', to: 'admin#tail_logfile'
    get 'settings', to: 'admin#settings'
    get 'user_visits', to: 'admin#user_visits'
    get 'edit_user', to: 'admin#edit_user'
    get 'autoflag', to: 'admin#autoflag'
    get 'ok_flag', to: 'admin#ok_flag'
    get 'revert_flag', to: 'admin#revert_flag'
    get 'delete_user', to: 'admin#delete_user'
    get 'view_processing_log', to: 'admin#view_processing_log'
    get 'delete_upload', to: 'admin#delete_upload'
    get 'visit_deeds', to: 'admin#visit_deeds'
    get 'visit_actions', to: 'admin#visit_actions'
    get 'expunge_confirmation', to: 'admin#expunge_confirmation'
    get 'ok_user', to: 'admin#ok_user'
    get 'downgrade', to: 'admin#downgrade'
    post 'update', to: 'admin#update'
    patch 'update_user', to: 'admin#update_user'
    patch 'expunge_user', to: 'admin#expunge_user'
  end

  scope 'facets', as: 'facets' do
    get 'enable', to: 'facets#enable'
    get 'disable', to: 'facets#disable'
    post 'update', to: 'facets#update'
    get ':collection_id/localize', to: 'facets#localize', as: 'localize'
    post 'update_localization', to: 'facets#update_localization'
  end

  scope 'collection', as: 'collection' do
    get 'new', to: 'collection#new'
    get 'delete', to: 'collection#delete'
    get 'activity_download', to: 'collection#activity_download'
    get 'show', to: 'collection#show', as: 'show'
    get 'toggle_collection_active', to: 'collection#toggle_collection_active'
    get 'toggle_collection_api_access', to: 'collection#toggle_collection_api_access'
    get 'contributors_download', to: 'collection#contributors_download'
    get 'enable_fields', to: 'collection#enable_fields'
    get 'enable_metadata_entry', to: 'collection#enable_metadata_entry'
    get 'enable_document_sets', to: 'collection#enable_document_sets'
    get 'enable_messageboards', to: 'collection#enable_messageboards'
    get 'enable_ocr', to: 'collection#enable_ocr'
    get 'disable_ocr', to: 'collection#disable_ocr'
    get 'blank_collection', to: 'collection#blank_collection'
    get 'edit', to: 'collection#edit'
    get ':collection_id/edit_owners', to: 'collection#edit_owners', as: 'edit_owners'
    post 'add_reviewer', to: 'collection#add_reviewer'
    get ':collection_id/edit_reviewers', to: 'collection#edit_reviewers', as: 'edit_reviewers'
    post 'remove_reviewer', to: 'collection#remove_reviewer'
    get 'disable_document_sets', to: 'collection#disable_document_sets'
    get 'disable_messageboards', to: 'collection#disable_messageboards'
    get 'disable_fields', to: 'collection#disable_fields'
    get 'disable_metadata_entry', to: 'collection#disable_metadata_entry'
    get 'publish_collection', to: 'collection#publish_collection'
    get ':collection_id/edit_collaborators', to: 'collection#edit_collaborators', as: 'edit_collaborators'
    get 'restrict_collection', to: 'collection#restrict_collection'
    get 'restrict_transcreibed', to: 'collection#restrict_transcribed'
    post 'add_collaborator', to: 'collection#add_collaborator'
    post 'remove_collaborator', to: 'collection#remove_collaborator'
    post 'add_owner', to: 'collection#add_owner'
    post 'remove_owner', to: 'collection#remove_owner'
    post 'create', to: 'collection#create'
    get ':collection_id/search_users', to: 'collection#search_users', as: 'search_users'
    match 'update/:id', to: 'collection#update', via: %i[get post], as: 'update'

    scope 'metadata', as: 'metadata' do
      get ':id/example', to: 'metadata#example', as: :example
      get ':id/upload', to: 'metadata#upload', as: :upload
      get 'csv_error', to: 'metadata#csv_error'
      post 'create', to: 'metadata#create'
    end

    scope 'editor_button', as: 'editor_button' do
      get ':collection_id/edit', to: 'collection#edit_buttons', as: 'edit'
      post ':collection_id/edit', to: 'collection#update_buttons', as: 'update'
    end
  end

  scope 'work', as: 'work' do
    get 'delete', to: 'work#delete'
    get 'update_featured_page', to: 'work#update_featured_page'
    get 'pages_tab', to: 'work#pages_tab'
    get 'edit', to: 'work#edit'
    get 'revert', to: 'work#revert'
    post 'update', to: 'work#update'
    post 'create', to: 'work#create'
    patch 'update_work', to: 'work#update_work'
  end

  scope 'page', as: 'page' do
    get 'new', to: 'page#new'
    get 'delete', to: 'page#delete'
    get 'reorder_page', to: 'page#reorder_page'
    get 'edit', to: 'page#edit'
    get 'rotate', to: 'page#rotate'
    post 'update', to: 'page#update'
    post 'create', to: 'page#create'
  end

  scope 'article', as: 'article' do
    get 'list', to: 'article#list'
    get 'tooltip', to: 'article#tooltip'
    get 'delete', to: 'article#delete'
    get 'show', to: 'article#show'
    post 'combine_duplicate', to: 'article#combine_duplicate'
    post 'article_category', to: 'article#article_category'
  end

  scope 'export', as: 'export' do
    get '/', to: 'export#index'
    get 'export_work', to: 'export#export_work'
    get 'export_all_works', to: 'export#export_all_works'
    post ':collection_id/:work_id/printable', to: 'export#printable', as: 'printable'
    get 'show', to: 'export#show'
    get ':work_id/tei', to: 'export#tei', as: 'tei'
    get 'subject_csv', to: 'export#subject_index_csv'
    get 'subject_details_csv', to: 'export#subject_details_csv'
    get 'subject_coocurrence_csv', to: 'export#subject_coocurrence_csv'
    get 'table_csv', to: 'export#table_csv'
    get 'export_all_tables', to: 'export#export_all_tables'
    get ':collection_id/work_metadata_csv', to: 'export#work_metadata_csv', as: 'work_metadata'
    get 'edit_contentdm_credentials', to: 'export#edit_contentdm_credentials'
    post 'update_contentdm_credentials', to: 'export#update_contentdm_credentials'
    get 'work_plaintext_verbatim', to: 'export#work_plaintext_verbatim'
  end

  scope 'bulk_export', as: 'bulk_export' do
    get ':collection_id/new', to: 'bulk_export#new', as: 'new'
    post ':collection_id/new', to: 'bulk_export#create', as: 'create'
    post ':collection_id/work_create', to: 'bulk_export#create_for_work', as: 'create_for_work'
    get '/', to: 'bulk_export#index', as: 'index'
    get ':bulk_export_id', to: 'bulk_export#show', as: 'show'
    get ':bulk_export_id/download', to: 'bulk_export#download', as: 'download'
  end

  scope 'ia', as: 'ia' do
    get 'import_work', to: 'ia#import_work'
    get 'book_form', to: 'ia#ia_book_form'
    get 'manage', to: 'ia#manage'
    get 'mark_beginning', to: 'ia#mark_beginning'
    get 'mark_end', to: 'ia#mark_end'
    get 'title_from_ocr_top', to: 'ia#title_from_ocr_top'
    get 'title_from_ocr_bottom', to: 'ia#title_from_ocr_bottom'
    post 'convert', to: 'ia#convert'
    post 'import_work', to: 'ia#import_work'
    match 'confirm_import', to: 'ia#confirm_import', via: %i[get post]
  end

  scope 'dashboard', as: 'dashboard' do
    get '/' => 'dashboard#index'
    get 'owner' => 'dashboard#owner'
    get 'watchlist' => 'dashboard#watchlist'
    get 'startproject', to: 'dashboard#startproject'
    get 'summary', to: 'dashboard#summary'
    get 'exports', to: 'dashboard#exports'
    get 'collaborator_time_export', to: 'dashboard#collaborator_time_export'
    post 'new_upload', to: 'dashboard#new_upload'
    post 'create_work', to: 'dashboard#create_work'
  end

  scope 'category', as: 'category' do
    get 'edit', to: 'category#edit'
    get 'add_new', to: 'category#add_new'
    get 'enable_gis', to: 'category#enable_gis'
    get 'disable_gis', to: 'category#disable_gis'
    get 'delete', to: 'category#delete'
    post 'create', to: 'category#create'
    patch 'update', to: 'category#update'
  end

  scope 'transcribe', as: 'transcribe' do
    get 'mark_page_blank', to: 'transcribe#mark_page_blank'
    get 'display_page', to: 'transcribe#display_page'
    get 'assign_categories', to: 'transcribe#assign_categories'
    get 'guest', to: 'transcribe#guest'
    get 'edit_fields', to: 'transcribe#edit_fields'

app/controllers/export_controller.rb
require 'contentdm_translator'

class ExportController < ApplicationController
  require 'zip'
  include CollectionHelper, ExportHelper, ExportService

  # no layout if xhr request
  layout Proc.new { |controller| controller.request.xhr? ? false : nil } #, :only => [:update, :update_profile]

  def index
    # @collection = Collection.friendly.find(params[:collection_id])
    #check if there are any translated works in the collection
    if @collection.works.where(supports_translation: true).exists?
      @header = "Translated"
    else
      @header = "Transcribed"
    end

    @works = @collection.works.includes(:work_statistic).paginate(page: params[:page], per_page: 15)

    @table_export = @collection.works.joins(:table_cells).where.not(table_cells: {work_id: nil}).distinct
  end

  def show
    xhtml = work_to_xhtml(@work)

    render :text => xhtml, :layout => false
  end

  def printable
    output_file = export_printable(@work, params[:edition], params[:format])    

    if params[:format] == 'pdf'
      content_type = "application/pdf"
    elsif params[:format] == 'doc'
      content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    end

    # spew the output to the browser
    send_data(File.read(output_file), 
      filename: File.basename(output_file), 
      :content_type => content_type)
    cookies['download_finished'] = 'true'
  end

  def text
    @work = Work.includes(pages: [:notes, {page_versions: :user}]).find_by(id: params[:work_id])
    render :layout => false
  end

  def transcript
    @work = Work.includes(pages: [:notes, {page_versions: :user}]).find_by(id: params[:work_id])
    render :layout => false
  end

  def translation
    @work = Work.includes(pages: [:notes, {page_versions: :user}]).find_by(id: params[:work_id])
    render :layout => false
  end

  def tei
    tei_xml = work_to_tei(@work, current_user)

    render :text => tei_xml, :content_type => "application/xml", :layout => false
  end

  def subject_details_csv
    send_data(@collection.export_subject_details_as_csv,
              :filename => "fromthepage_subject_details_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end


  def subject_coocurrence_csv
    send_data(@collection.export_subject_coocurrence_as_csv,
              :filename => "fromthepage_subject_coocurrence_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end

  def subject_distribution_csv
    send_data(@collection.export_subject_distribution_as_csv(@article),
              :filename => "fromthepage_subject_distribution_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end

  def subject_index_csv
    send_data(@collection.export_subject_index_as_csv,
              :filename => "fromthepage_subject_index_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end

  def work_metadata_csv
    send_data(export_work_metadata_as_csv(@collection),
              :filename => "fromthepage_work_metadata_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end


  def table_csv
    send_data(export_tables_as_csv(@work),
              :filename => "fromthepage_tables_export_#{@work.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'
  end



  def export_all_tables
    send_data(export_tables_as_csv(@collection),
              :filename => "fromthepage_tables_export_#{@collection.id}_#{Time.now.utc.iso8601}.csv",
              :type => "application/csv")
    cookies['download_finished'] = 'true'

  end

  def page_plaintext_verbatim
    render  :layout => false, :content_type => "text/plain", :plain => @page.verbatim_transcription_plaintext
  end

  def page_plaintext_translation_verbatim
    render  :layout => false, :content_type => "text/plain", :plain => @page.verbatim_translation_plaintext
  end

  def page_plaintext_emended
    render  :layout => false, :content_type => "text/plain", :plain => @page.emended_transcription_plaintext
  end

  def page_plaintext_translation_emended
    render  :layout => false, :content_type => "text/plain", :plain => @page.emended_translation_plaintext
  end

  def page_plaintext_searchable
    render  :layout => false, :content_type => "text/plain", :plain => @page.search_text
  end

  def work_plaintext_verbatim
    render  :layout => false, :content_type => "text/plain", :plain => @work.verbatim_transcription_plaintext
  end

  def work_plaintext_translation_verbatim
    render  :layout => false, :content_type => "text/plain", :plain => @work.verbatim_translation_plaintext
  end

  def work_plaintext_emended
    render  :layout => false, :content_type => "text/plain", :plain => @work.emended_transcription_plaintext
  end

  def work_plaintext_translation_emended
    render  :layout => false, :content_type => "text/plain", :plain => @work.emended_translation_plaintext
  end

  def work_plaintext_searchable
    render  :layout => false, :content_type => "text/plain", :plain => @work.searchable_plaintext
  end


  def edit_contentdm_credentials
    # display the edit form
  end

  def update_contentdm_credentials
    # test credentials
    license_key = params[:collection][:license_key]
    contentdm_user_name = params[:contentdm_user_name]
    contentdm_password = params[:contentdm_password]
    error_message, fts_field = ContentdmTranslator.fts_field_for_collection(@collection)

    # persist license key so the user doesn't have to retype it
    if error_message.blank? || !error_message.match(/license.*invalid/)
      @collection.license_key = license_key
      @collection.save!
    end

    # redirect to or render edit screen with error
    if error_message
      flash[:error] = error_message
      render :action => :edit_contentdm_credentials, :collection_id => @collection.id
      return
    end

    # pass credentials, FTS field, and search to background job
    log_file = ContentdmTranslator.log_file(@collection)
    unless Dir.exist? File.dirname(log_file)
      FileUtils.mkdir_p(File.dirname(log_file))
    end    
    cmd = "rake fromthepage:cdm_transcript_export[#{@collection.id}] > #{log_file} 2>&1 &"
    logger.info(cmd)
    system({'contentdm_username' => contentdm_user_name, 'contentdm_password' => contentdm_password, 'contentdm_license' => license_key}, cmd)

    # display results somehow
    flash[:notice] = t('.updating_contentdm_message')
    ajax_redirect_to :action => :index, :collection_id => @collection.id
  end

  def version
    version = Fromthepage::Application::Version
    database = ActiveRecord::Migrator.current_version

    render json: { software: version,
                   database: database }
  end


end

app/views/export/edit_contentdm_credentials.html.slim
.litebox-embed(style="width:550px")
  -flash.each do |type, message|
    -flash_icon = { 'notice' => '#icon-check-sign', 'alert' => '#icon-warning-sign', 'error' => '#icon-remove-sign' }
    .flash(class='flash-#{type}')
      span.flash_message
        =svg_symbol flash_icon[type], class: 'icon'
        span =message
      a.flash_close &times;


  h1 =t('.contentdm_credentials')
  p =t('.contentdm_credentials_description')

  =form_for(@collection, url: { :action => 'update_contentdm_credentials' }, :method => :post) do |f|
    =validation_summary @collection.errors
    =hidden_field_tag :collection_id, @collection.id
    table.form
      tr
        th =f.label :license_key, t('.license_key')
        td.w100 =f.text_field :license_key
      tr
        th =f.label :contentdm_user_name, t('.contentdm_user_name')
        td.w100 =text_field_tag :contentdm_user_name
      tr
        th =f.label :contentdm_password, t('.contentdm_password')
        td.w100 =password_field_tag :contentdm_password
    .toolbar
      .toolbar_group.aright =f.button t('.connect')

app/views/export/facing_edition.html.erb
<% unless @edition_type == 'text_only'%>

<%= @work.title %> {.work-title}
=======================


\newpage
### Metadata
<p>
<%= t('.export_metadata', work: @work.title, collection: @work.collection.title, time: Time.now) %>
</p>

<% 
  xml_metadata = @work.merge_metadata.map{|e| "#{e['label']}: #{e['value']}"}.join("<lb/>\n")
%>
<%= raw(xml_to_pandoc_md("<p>#{xml_metadata}</p>", true, true, nil, false)) %>
\newpage
<% end %>

<% @work.pages.includes(:notes, :ia_leaf, :sc_canvas).each do |page| %>

<% if @edition_type == 'facing'%>
\newpage
  <% if @work.sc_manifest %>
![<%= page.title %>](<%= page.sc_canvas.sc_resource_id %>)
  <% elsif page.ia_leaf %>
![<%= page.title %>](<%= page.ia_leaf.facsimile_url %>)
  <% else %>
![<%= page.title %>](<%= root_url %><%= file_to_url(page.canonical_facsimile_url) %>)
  <% end %>
\newpage
<% end %>

### <%= page.title %>
<%= raw(xml_to_pandoc_md(page.xml_text, @edition_type=='facing', true)) %>

<% if @work.supports_translation && !page.xml_translation.blank?%>
### <%= page.title %>
<%= raw(xml_to_pandoc_md(page.xml_translation, @edition_type=='facing', true)) %>
<% end %>

<% end %>

<% unless @edition_type == 'text_only'%>

\newpage
<%= t('.contributions_message') %>

<% contributor_ids = @work.deeds.group(:user_id).count.sort{|a,b| b[1] <=> a[1]}.map{|e| e[0]} %>
<% contributor_names = [] %>
<% contributor_ids.each do |user_id| %>
  <% user = User.find(user_id) 
    if user.real_name.blank?
      name = user.display_name
    else
      name = user.real_name
    end
    contributor_names << name unless name.blank?
  %>
<% end %>

<% if contributor_names.size > 1 %>
  <%= contributor_names[0..-2].join(', ') %> and <%= contributor_names.last %>
<% else %>
  <%= contributor_names.first %>
<% end %>
<% end %>

app/views/export/index.html.slim
=render({ :partial => '/shared/collection_tabs', :locals => { :selected => 6, :collection_id => @collection }})

h2.nomargin =t('.export_all_works')
p.big
  span.fright(style="margin-left: 30px")
    =link_to(bulk_export_new_path(:collection_id => @collection.slug), class: 'button btnExport', id: 'btnExportAll')
      =svg_symbol '#icon-export', class: 'icon'
      span =t('.export_all_works')

  span =t('.export_all_works_description')


-if ContentdmTranslator.collection_is_cdm?(@collection) && @collection.text_entry? && @collection.is_a?(Collection)
  h2 =t('.export_to_contentdm')
  p.big
    span.fright(style="margin-left: 30px")
      =link_to(export_edit_contentdm_credentials_path(:collection_id => @collection.id), {:class => 'button btnExport', :id => 'btnExportContentdm', :data => { :litebox => { :hash => "", :collection_id => @collection.id }, :collection_id => @collection.id}})
        =svg_symbol '#icon-export', class: 'icon'
        span =t('.export_to_contentdm')
    span =t('.export_to_contentdm_description')

-if @collection.text_entry?
  h2 =t('.export_individual_works')
  p.big =t('.export_individual_works_description')
  table.datagrid
    tr
      th.w80 =t('.work_title')
      th =t('.pages')
      -unless @collection.subjects_disabled
        th =t('.indexed')
      th #{@header}
      th =t('.review')
      th.w100 =t('.progress')
      th(colspan="6") =t('.export_as')

    -for work in @works
      -work_stats(work)

      tr
        td.big =link_to work.title, display_read_work_path(:work_id => work.id)
        td.nowrap.fgfaded =t('.n_pages', count: work.work_statistic.total_pages)
        -unless @collection.subjects_disabled
          td.nowrap.fgfaded.tocenter ="#{@progress_annotated}%"
        td.nowrap.fgfaded.tocenter ="#{@progress_completed}%"
        td.nowrap.fgfaded.tocenter ="#{@progress_review}%"
        td
          .progress
            -unless @collection.subjects_disabled
              span(style="width:#{@progress_annotated}%")
              span(style="width:#{@progress_completed - @progress_annotated}%")
              span(style="width:#{@progress_review}%")

            -else
              span(style="width:#{@progress_completed}%")
              span(style="width:#{@progress_review}%")

        td.nowrap
          =link_to(export_show_path(:work_id => work.id))
            =svg_symbol '#icon-export', class: 'icon'
            span= t('.html')
        td.nowrap
          =link_to(export_work_plaintext_verbatim_path(:work_id => work.id))
            =svg_symbol '#icon-export', class: 'icon'
            span =t('.plain_text')
        td.nowrap
          =link_to(export_tei_path(work.slug))
            =svg_symbol '#icon-export', class: 'icon'
            span= t('.tei')
        td.nowrap
          =link_to iiif_manifest_path(work.id)
            =svg_symbol '#icon-export', class: 'icon'
            span= t('.iiif')
        -unless work.table_cells.blank?
          -if work.table_cells.count < 10000
            td.nowrap
              =link_to({ :controller => 'export', :action => 'table_csv', :work_id => work.id }, class: 'btnCsvTblExport btnExport')
                =svg_symbol '#icon-export', class: 'icon'
                span =t('.table_csv')
        td.nowrap
          =link_to download_collection_work_path(@collection.owner, @collection, work), title: t('.more_export_formats')
            span =t('.more')

  =render(:partial => 'shared/pagination', :locals => { :model => @works, :entries_info => true })

  -unless @collection.subjects_disabled
    h2 =t('.export_subject_index')
    p.big
      span.fright(style="margin-left: 30px")
        =link_to(export_subject_csv_path(:collection_id => @collection.slug), class: 'button btnExport', id: 'btnCsvExport')
          =svg_symbol '#icon-export', class: 'icon'
          span =t('.export_subjects_as_csv')
      span =t('.export_subject_index_description')
    p.big
      span.fright(style="margin-left: 30px")
        =link_to(export_subject_details_csv_path(:collection_id => @collection.slug), class: 'button btnExport', id: 'btnCsvDetailExport')
          =svg_symbol '#icon-export', class: 'icon'
          span =t('.export_subject_details_as_csv')
      span =t('.export_subject_details_description')
    -if @collection.is_a? Collection
      p.big
        span.fright(style="margin-left: 30px")
          =link_to(export_subject_coocurrence_csv_path(:collection_id => @collection.slug), class: 'button btnExport', id: 'btnCsvCoocurrenceExport')
            =svg_symbol '#icon-export', class: 'icon'
            span =t('.export_subject_coocurrence_as_csv')
        span =t('.export_subject_coocurrence_description')

  -unless @table_export.blank?
    h2 =t('.export_all_tables')
    p.big
      span.fright(style="margin-left: 30px")
        =link_to(export_export_all_tables_path(:collection_id => @collection.slug), class: 'button btnExport', id: 'btnExportTables')
          =svg_symbol '#icon-export', class: 'icon'
          span =t('.export_all_table_data_as_csv')
      span =t('.export_all_tables_description')

h2 =t('.export_work_metadata')
p.big
  span.fright(style="margin-left: 30px")
    =link_to(export_work_metadata_path(@collection.slug), class: 'button btnExport', id: 'btnExportMetadata')
      =svg_symbol '#icon-export', class: 'icon'
      span =t('.export_work_metadata_as_csv')
  span =t('.export_work_metadata_description')

h2= t('.api')
p
  =t('.iiif_api_description', link: link_to(t('.here'), 'https://github.com/benwbrum/fromthepage/wiki/FromThePage-Support-for-the-IIIF-Presentation-API-and-Web-Annotations')).html_safe

p
  =t('.iiif_collection_api_endpoint', link: link_to(iiif_collection_url(@collection.slug, only_path: false),
                                                    iiif_collection_url(@collection.slug, only_path: false))).html_safe

=render({ :partial => '/shared/collection_footer' })

-content_for :javascript
  javascript:
    $(function() {
      // Remove 'page_busy' spinner once CSV download finished
      // Cookie should be set to 'true' in the controller method
      $('.btnExport').on('click', function() {
        Cookies.remove('download_finished', {path: '/'});
        var downloadCheckTimer = window.setInterval(function() {
          var cookie = Cookies.get('download_finished');
          if(cookie === 'true') {
            $('html').removeClass('page-busy');
            window.clearInterval(downloadCheckTimer);
          }
        }, 1000);
      });
    });

app/views/export/translation.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title> <%= @work.title %></title>
  </head>

  <body>
    <h1 class="work-title"><%= @work.title %></h1>
    <div class="export-metadata"><%= t('.export_metadata', work: @work.title, collection: @collection.title, time: Time.now) %>
      <% unless @work.identifier.blank? %>
        <p><%= t('.identifier', work: @work.identifier) %></p>
      <% end %>
      <p>
        <%= t('.fromthepage_version', version: fromthepage_version) %>
      </p>
    </div>

    <hr />
    <% if @work.supports_translation %>
      <hr />
      <h2 class="divider"><%= t('.page_translations') %></h2>

      <div class="pages">
        <% @work.pages.each do |page| %>
        <div id="translation-<%=page.id%>">
          <h3><%= page.title %></h3>
          <div class="page-content">
            <%= raw(xml_to_html(page.xml_translation, true, true)) %>
          </div>
        </div>
        <br />
        <% if page.notes.present? %>
          <div class="page-notes">
            <strong><%= t('.notes') %></strong>
            <% page.notes.each do |note| %>
              <div>
                <p><span class="page-note-username"><%=note.user.display_name%></span></p>
                <p class="page-note-content"><%= sanitize(note.body, tags: %w(strong b em i a), attributes: %w(href))%></p>

              </div>
            <% end %>
          </div>
        <% end %>
        <% end %>
      </div>
    <% end %>
  </body>
</html>