config/routes.rb
Fromthepage::Application.routes.draw do
  # TODO: make the URL fall under user and collection profile
  scope ':user_slug' do
    scope ':collection_id' do
      mount Thredded::Engine => '/forum'
    end
  end

  namespace :emldict do
    get '/', to: 'base#index'
    resource :source
    resources :parsed, only: %i[index show], param: :collection_slug do
      get ':work_slug', to: 'parsed#work_show', as: :work_show
      get ':work_slug/export', to: 'parsed#work_export', as: :work_export
      get ':work_slug/needs-review', to: 'parsed#work_needs_review_show', as: :work_needs_review_show
    end
  end

  root to: 'static#landing_page'
  get '/blog' => redirect('https://fromthepage.com/blog/')

  devise_for :users,
             controllers: { masquerades: 'masquerades', registrations: 'registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'users/new_trial' => 'registrations#new_trial'
    get ':user_slug/sign_up', to: 'registrations#owner_new', as: 'new_for_owner'
    post 'registrations/choose_provider', to: 'registrations#choose_saml'
    post 'registrations/set_provider', to: 'registrations#set_saml'
    match '/users/auth/saml/:identity_provider_id/callback',
          via: %i[get post],
          to: 'users/omniauth_callbacks#saml',
          as: 'user_omniauth_callback'

    match '/users/auth/saml/:identity_provider_id',
          via: %i[get post],
          to: 'users/omniauth_callbacks#passthru',
          as: 'user_omniauth_authorize'
  end

  iiif_for 'riiif/image', at: '/image-service'

  resources :notes

  scope 'admin', as: 'admin' do
    get '/' => 'admin#index'
    get 'collection_list', to: 'admin#collection_list'
    get 'work_list', to: 'admin#work_list'
    get 'owner_list', to: 'admin#owner_list'
    get 'user_list', to: 'admin#user_list'
    get 'flag_list', to: 'admin#flag_list'
    get 'moderation', to: 'admin#moderation'
    get 'uploads', to: 'admin#uploads'
    get 'tail_logfile', to: 'admin#tail_logfile'
    get 'settings', to: 'admin#settings'
    get 'user_visits', to: 'admin#user_visits'
    get 'edit_user', to: 'admin#edit_user'
    get 'autoflag', to: 'admin#autoflag'
    get 'ok_flag', to: 'admin#ok_flag'
    get 'revert_flag', to: 'admin#revert_flag'
    get 'delete_user', to: 'admin#delete_user'
    get 'view_processing_log', to: 'admin#view_processing_log'
    get 'delete_upload', to: 'admin#delete_upload'
    get 'visit_deeds', to: 'admin#visit_deeds'
    get 'visit_actions', to: 'admin#visit_actions'
    get 'expunge_confirmation', to: 'admin#expunge_confirmation'
    get 'ok_user', to: 'admin#ok_user'
    get 'downgrade', to: 'admin#downgrade'
    post 'update', to: 'admin#update'
    patch 'update_user', to: 'admin#update_user'
    patch 'expunge_user', to: 'admin#expunge_user'
  end

  scope 'facets', as: 'facets' do
    get 'enable', to: 'facets#enable'
    get 'disable', to: 'facets#disable'
    post 'update', to: 'facets#update'
    get ':collection_id/localize', to: 'facets#localize', as: 'localize'
    post 'update_localization', to: 'facets#update_localization'
  end

  scope 'collection', as: 'collection' do
    get 'new', to: 'collection#new'
    get 'delete', to: 'collection#delete'
    get 'activity_download', to: 'collection#activity_download'
    get 'show', to: 'collection#show', as: 'show'
    get 'toggle_collection_active', to: 'collection#toggle_collection_active'
    get 'toggle_collection_api_access', to: 'collection#toggle_collection_api_access'
    get 'contributors_download', to: 'collection#contributors_download'
    get 'enable_fields', to: 'collection#enable_fields'
    get 'enable_metadata_entry', to: 'collection#enable_metadata_entry'
    get 'enable_document_sets', to: 'collection#enable_document_sets'
    get 'enable_messageboards', to: 'collection#enable_messageboards'
    get 'enable_ocr', to: 'collection#enable_ocr'
    get 'disable_ocr', to: 'collection#disable_ocr'
    get 'blank_collection', to: 'collection#blank_collection'
    get 'edit', to: 'collection#edit'
    get ':collection_id/edit_owners', to: 'collection#edit_owners', as: 'edit_owners'
    post 'add_reviewer', to: 'collection#add_reviewer'
    get ':collection_id/edit_reviewers', to: 'collection#edit_reviewers', as: 'edit_reviewers'
    post 'remove_reviewer', to: 'collection#remove_reviewer'
    get 'disable_document_sets', to: 'collection#disable_document_sets'
    get 'disable_messageboards', to: 'collection#disable_messageboards'
    get 'disable_fields', to: 'collection#disable_fields'
    get 'disable_metadata_entry', to: 'collection#disable_metadata_entry'
    get 'publish_collection', to: 'collection#publish_collection'
    get ':collection_id/edit_collaborators', to: 'collection#edit_collaborators', as: 'edit_collaborators'
    get 'restrict_collection', to: 'collection#restrict_collection'
    get 'restrict_transcreibed', to: 'collection#restrict_transcribed'
    post 'add_collaborator', to: 'collection#add_collaborator'
    post 'remove_collaborator', to: 'collection#remove_collaborator'
    post 'add_owner', to: 'collection#add_owner'
    post 'remove_owner', to: 'collection#remove_owner'
    post 'create', to: 'collection#create'
    get ':collection_id/search_users', to: 'collection#search_users', as: 'search_users'
    match 'update/:id', to: 'collection#update', via: %i[get post], as: 'update'

    scope 'metadata', as: 'metadata' do
      get ':id/example', to: 'metadata#example', as: :example
      get ':id/upload', to: 'metadata#upload', as: :upload
      get 'csv_error', to: 'metadata#csv_error'
      post 'create', to: 'metadata#create'
    end

    scope 'editor_button', as: 'editor_button' do
      get ':collection_id/edit', to: 'collection#edit_buttons', as: 'edit'
      post ':collection_id/edit', to: 'collection#update_buttons', as: 'update'
    end
  end

  scope 'work', as: 'work' do
    get 'delete', to: 'work#delete'
    get 'update_featured_page', to: 'work#update_featured_page'
    get 'pages_tab', to: 'work#pages_tab'
    get 'edit', to: 'work#edit'
    get 'revert', to: 'work#revert'
    post 'update', to: 'work#update'
    post 'create', to: 'work#create'
    patch 'update_work', to: 'work#update_work'
  end

  scope 'page', as: 'page' do
    get 'new', to: 'page#new'
    get 'delete', to: 'page#delete'
    get 'reorder_page', to: 'page#reorder_page'
    get 'edit', to: 'page#edit'
    get 'rotate', to: 'page#rotate'
    post 'update', to: 'page#update'
    post 'create', to: 'page#create'
  end

  scope 'article', as: 'article' do
    get 'list', to: 'article#list'
    get 'tooltip', to: 'article#tooltip'
    get 'delete', to: 'article#delete'
    get 'show', to: 'article#show'
    post 'combine_duplicate', to: 'article#combine_duplicate'
    post 'article_category', to: 'article#article_category'
  end

  scope 'export', as: 'export' do
    get '/', to: 'export#index'
    get 'export_work', to: 'export#export_work'
    get 'export_all_works', to: 'export#export_all_works'
    post ':collection_id/:work_id/printable', to: 'export#printable', as: 'printable'
    get 'show', to: 'export#show'
    get ':work_id/tei', to: 'export#tei', as: 'tei'
    get 'subject_csv', to: 'export#subject_index_csv'
    get 'subject_details_csv', to: 'export#subject_details_csv'
    get 'subject_coocurrence_csv', to: 'export#subject_coocurrence_csv'
    get 'table_csv', to: 'export#table_csv'
    get 'export_all_tables', to: 'export#export_all_tables'
    get ':collection_id/work_metadata_csv', to: 'export#work_metadata_csv', as: 'work_metadata'
    get 'edit_contentdm_credentials', to: 'export#edit_contentdm_credentials'
    post 'update_contentdm_credentials', to: 'export#update_contentdm_credentials'
    get 'work_plaintext_verbatim', to: 'export#work_plaintext_verbatim'
  end

  scope 'bulk_export', as: 'bulk_export' do
    get ':collection_id/new', to: 'bulk_export#new', as: 'new'
    post ':collection_id/new', to: 'bulk_export#create', as: 'create'
    post ':collection_id/work_create', to: 'bulk_export#create_for_work', as: 'create_for_work'
    get '/', to: 'bulk_export#index', as: 'index'
    get ':bulk_export_id', to: 'bulk_export#show', as: 'show'
    get ':bulk_export_id/download', to: 'bulk_export#download', as: 'download'
  end

  scope 'ia', as: 'ia' do
    get 'import_work', to: 'ia#import_work'
    get 'book_form', to: 'ia#ia_book_form'
    get 'manage', to: 'ia#manage'
    get 'mark_beginning', to: 'ia#mark_beginning'
    get 'mark_end', to: 'ia#mark_end'
    get 'title_from_ocr_top', to: 'ia#title_from_ocr_top'
    get 'title_from_ocr_bottom', to: 'ia#title_from_ocr_bottom'
    post 'convert', to: 'ia#convert'
    post 'import_work', to: 'ia#import_work'
    match 'confirm_import', to: 'ia#confirm_import', via: %i[get post]
  end

  scope 'dashboard', as: 'dashboard' do
    get '/' => 'dashboard#index'
    get 'owner' => 'dashboard#owner'
    get 'watchlist' => 'dashboard#watchlist'
    get 'startproject', to: 'dashboard#startproject'
    get 'summary', to: 'dashboard#summary'
    get 'exports', to: 'dashboard#exports'
    get 'collaborator_time_export', to: 'dashboard#collaborator_time_export'
    post 'new_upload', to: 'dashboard#new_upload'
    post 'create_work', to: 'dashboard#create_work'
  end

  scope 'category', as: 'category' do
    get 'edit', to: 'category#edit'
    get 'add_new', to: 'category#add_new'
    get 'enable_gis', to: 'category#enable_gis'
    get 'disable_gis', to: 'category#disable_gis'
    get 'delete', to: 'category#delete'
    post 'create', to: 'category#create'
    patch 'update', to: 'category#update'
  end

  scope 'transcribe', as: 'transcribe' do
    get 'mark_page_blank', to: 'transcribe#mark_page_blank'
    get 'display_page', to: 'transcribe#display_page'
    get 'assign_categories', to: 'transcribe#assign_categories'
    get 'guest', to: 'transcribe#guest'
    get 'edit_fields', to: 'transcribe#edit_fields'

app/controllers/emldict/base_controller.rb
# frozen_string_literal: true

class Emldict::BaseController < ActionController::Base
  def index
    render
  end
end

app/controllers/emldict/parsed_controller.rb
# frozen_string_literal: true

class Emldict::ParsedController < Emldict::BaseController
  before_action :load_collection, except: :index
  before_action :load_work, except: %i[index show]
  before_action :load_page, only: %i[work_show work_export]
  before_action :load_parse_output, only: %i[work_show work_export]

  def index
    render
  end

  def show
    render
  end

  def work_show
    response_status = if @parse_exception
      :unprocessable_entity
    else
      :ok
    end
    render status: response_status
  end

  def work_export
    if @parse_exception
      render status: :unprocessable_entity, plain: @parse_exception and return
    end

    csv = Emldict::DictpressCsvExportService.new(@parse_output).process
    render status: :ok, plain: csv
  end

  def work_needs_review_show
    render
  end

  private

    def load_collection
      @collection = Collection.find_by(slug: params[:collection_slug] || params[:parsed_collection_slug])
    end

    def load_work
      @work = Work.find_by(slug: params[:work_slug])
    end

    def is_number?(obj)
      obj.to_s == obj.to_i.to_s
    end

    def load_page
      @page = if is_number?(params[:page])
        @work.pages.find_by(position: params[:page])
      else
        nil
      end
    end

    def load_parse_output
      @parse_input = if @page
        @page.contents_stiched
      else
        @work.pages.map(&:contents_with_emlref).join("\n")
      end

      begin
        @parse_output = Emldict::Rsp::ParserService.new(@parse_input).process
      rescue Exception => exception
        @parse_exception = exception
      end
    end
end

app/controllers/emldict/sources_controller.rb
# frozen_string_literal: true

class Emldict::SourcesController < Emldict::BaseController
  before_action :load_page_url

  def show
    redirect_to @url
  end

  private

    def load_page_url
      like_clause_one = "%word '#{word_param}'%"
      like_clause_two = "%word \"#{word_param}\"%"
      pages = Page.where("source_text LIKE ? OR source_text LIKE ?", like_clause_one, like_clause_two)

      render "not_found" and return if pages.size === 0
      render "results" and return if pages.size > 1

      page = pages.first
      @url = collection_display_page_path(page.collection.owner, page.collection, page.work, page)
    end

    def word_param
      params.require(:word)
    end
end

app/views/emldict/parsed/index.html.erb
<h1>List of collections</h1>
<ul>
  <%=
  Collection.order(:title).all.map { |collection|
    "<li><a href='/emldict/parsed/#{collection.slug}'>#{collection.title}</a></li>"
  }.join("").html_safe
  %>
</ul>

app/views/emldict/parsed/show.html.erb
<h1>List of works</h1>
<ul>
  <%=
  # <a href='/emldict/parsed/#{collection.slug}'>#{collection.title}</a>
  @collection.works.order(:title).all.map { |work|
    work_url = emldict_parsed_work_show_path(parsed_collection_slug: @collection.slug, work_slug: work.slug)
    "<li>#{link_to(work.title, work_url)}</li>"
  }.join("").html_safe
  %>
</ul>

app/views/emldict/parsed/work_needs_review_show.html.erb
  <h1><%= @work.title %></h1>
<div class="all-pages-link-wrapper">
  <%= link_to("All pages combined parsed output", emldict_parsed_work_show_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug), class: "button") %>
  <%= link_to("Needs review pages", emldict_parsed_work_needs_review_show_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug), class: "button") %>
</div>

<%
export_url = emldict_parsed_work_export_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug, page: params[:page])

paginate_page_param = if @page
  params[:page]
else
  1
end
%>

<p>Pages that have "needs_review" in it.</p>

<ul>
  <% Page.where('source_text LIKE "%needs_review%"').map do |page| %>
    <li><%= link_to("Page #{page.position}", collection_transcribe_page_path(page.collection.owner, page.collection, page.work, page), target: "blank") %></li>
  <% end %>
</ul>

<style>
.pagination, .all-pages-link-wrapper {
  display: table;
  margin: 30px auto;
}
.pagination a, .pagination em, .pagination span, .button {
  border: 1px solid #000;
  padding: 4px 8px;
  margin: 0 12px;
}
</style>

app/views/emldict/parsed/work_show.html.erb
<h1><%= @work.title %></h1>
<div class="all-pages-link-wrapper">
  <%= link_to("All pages combined parsed output", emldict_parsed_work_show_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug), class: "button") %>
  <%= link_to("Needs review pages", emldict_parsed_work_needs_review_show_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug), class: "button") %>
</div>

<%
export_url = emldict_parsed_work_export_path(parsed_collection_slug: @collection.slug, work_slug: @work.slug, page: params[:page])

paginate_page_param = if @page
  params[:page]
else
  1
end
%>

<%= will_paginate(@work.pages.order(:position).paginate(page: paginate_page_param, per_page: 1)) %>

<% if @page %>
  <h1>Page <%= @page.position %></h1>
  <ul>
    <li>Page title: <%= @page.title %></li>
    <li>Page position: <%= @page.position %></li>
  </ul>
<% else %>
  <h1>All pages combined</h1>
<% end %>

<% if @parse_exception.nil? %>
  <h2>Words - <%= @parse_output.size %></h2>
  <a class="button" href="<%= export_url %>">Export as CSV</a>
  <pre><code><%= JSON.pretty_generate(@parse_output) %></code></pre>
<% else %>
  There was an error in processing some pages.
  <pre><code style="width: 100%;white-space: pre-wrap;"><%= @parse_exception %></code></pre>
<% end %>

<style>
.pagination, .all-pages-link-wrapper {
  display: table;
  margin: 30px auto;
}
.pagination a, .pagination em, .pagination span, .button {
  border: 1px solid #000;
  padding: 4px 8px;
  margin: 0 12px;
}
</style>