config/routes.rb
Fromthepage::Application.routes.draw do
  # TODO: make the URL fall under user and collection profile
  scope ':user_slug' do
    scope ':collection_id' do
      mount Thredded::Engine => '/forum'
    end
  end

  namespace :emldict do
    get '/', to: 'base#index'
    resource :source
    resources :parsed, only: %i[index show], param: :collection_slug do
      get ':work_slug', to: 'parsed#work_show', as: :work_show
      get ':work_slug/export', to: 'parsed#work_export', as: :work_export
      get ':work_slug/needs-review', to: 'parsed#work_needs_review_show', as: :work_needs_review_show
    end
  end

  root to: 'static#landing_page'
  get '/blog' => redirect('https://fromthepage.com/blog/')

  devise_for :users,
             controllers: { masquerades: 'masquerades', registrations: 'registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'users/new_trial' => 'registrations#new_trial'
    get ':user_slug/sign_up', to: 'registrations#owner_new', as: 'new_for_owner'
    post 'registrations/choose_provider', to: 'registrations#choose_saml'
    post 'registrations/set_provider', to: 'registrations#set_saml'
    match '/users/auth/saml/:identity_provider_id/callback',
          via: %i[get post],
          to: 'users/omniauth_callbacks#saml',
          as: 'user_omniauth_callback'

    match '/users/auth/saml/:identity_provider_id',
          via: %i[get post],
          to: 'users/omniauth_callbacks#passthru',
          as: 'user_omniauth_authorize'
  end

  iiif_for 'riiif/image', at: '/image-service'

  resources :notes

  scope 'admin', as: 'admin' do
    get '/' => 'admin#index'
    get 'collection_list', to: 'admin#collection_list'
    get 'work_list', to: 'admin#work_list'
    get 'owner_list', to: 'admin#owner_list'
    get 'user_list', to: 'admin#user_list'
    get 'flag_list', to: 'admin#flag_list'
    get 'moderation', to: 'admin#moderation'
    get 'uploads', to: 'admin#uploads'
    get 'tail_logfile', to: 'admin#tail_logfile'
    get 'settings', to: 'admin#settings'
    get 'user_visits', to: 'admin#user_visits'
    get 'edit_user', to: 'admin#edit_user'
    get 'autoflag', to: 'admin#autoflag'
    get 'ok_flag', to: 'admin#ok_flag'
    get 'revert_flag', to: 'admin#revert_flag'
    get 'delete_user', to: 'admin#delete_user'
    get 'view_processing_log', to: 'admin#view_processing_log'
    get 'delete_upload', to: 'admin#delete_upload'
    get 'visit_deeds', to: 'admin#visit_deeds'
    get 'visit_actions', to: 'admin#visit_actions'
    get 'expunge_confirmation', to: 'admin#expunge_confirmation'
    get 'ok_user', to: 'admin#ok_user'
    get 'downgrade', to: 'admin#downgrade'
    post 'update', to: 'admin#update'
    patch 'update_user', to: 'admin#update_user'
    patch 'expunge_user', to: 'admin#expunge_user'
  end

  scope 'facets', as: 'facets' do
    get 'enable', to: 'facets#enable'
    get 'disable', to: 'facets#disable'
    post 'update', to: 'facets#update'
    get ':collection_id/localize', to: 'facets#localize', as: 'localize'
    post 'update_localization', to: 'facets#update_localization'
  end

  scope 'collection', as: 'collection' do
    get 'new', to: 'collection#new'
    get 'delete', to: 'collection#delete'
    get 'activity_download', to: 'collection#activity_download'
    get 'show', to: 'collection#show', as: 'show'
    get 'toggle_collection_active', to: 'collection#toggle_collection_active'
    get 'toggle_collection_api_access', to: 'collection#toggle_collection_api_access'
    get 'contributors_download', to: 'collection#contributors_download'
    get 'enable_fields', to: 'collection#enable_fields'
    get 'enable_metadata_entry', to: 'collection#enable_metadata_entry'
    get 'enable_document_sets', to: 'collection#enable_document_sets'
    get 'enable_messageboards', to: 'collection#enable_messageboards'
    get 'enable_ocr', to: 'collection#enable_ocr'
    get 'disable_ocr', to: 'collection#disable_ocr'
    get 'blank_collection', to: 'collection#blank_collection'
    get 'edit', to: 'collection#edit'
    get ':collection_id/edit_owners', to: 'collection#edit_owners', as: 'edit_owners'
    post 'add_reviewer', to: 'collection#add_reviewer'
    get ':collection_id/edit_reviewers', to: 'collection#edit_reviewers', as: 'edit_reviewers'
    post 'remove_reviewer', to: 'collection#remove_reviewer'
    get 'disable_document_sets', to: 'collection#disable_document_sets'
    get 'disable_messageboards', to: 'collection#disable_messageboards'
    get 'disable_fields', to: 'collection#disable_fields'
    get 'disable_metadata_entry', to: 'collection#disable_metadata_entry'
    get 'publish_collection', to: 'collection#publish_collection'
    get ':collection_id/edit_collaborators', to: 'collection#edit_collaborators', as: 'edit_collaborators'
    get 'restrict_collection', to: 'collection#restrict_collection'
    get 'restrict_transcreibed', to: 'collection#restrict_transcribed'
    post 'add_collaborator', to: 'collection#add_collaborator'
    post 'remove_collaborator', to: 'collection#remove_collaborator'
    post 'add_owner', to: 'collection#add_owner'
    post 'remove_owner', to: 'collection#remove_owner'
    post 'create', to: 'collection#create'
    get ':collection_id/search_users', to: 'collection#search_users', as: 'search_users'
    match 'update/:id', to: 'collection#update', via: %i[get post], as: 'update'

    scope 'metadata', as: 'metadata' do
      get ':id/example', to: 'metadata#example', as: :example
      get ':id/upload', to: 'metadata#upload', as: :upload
      get 'csv_error', to: 'metadata#csv_error'
      post 'create', to: 'metadata#create'
    end

    scope 'editor_button', as: 'editor_button' do
      get ':collection_id/edit', to: 'collection#edit_buttons', as: 'edit'
      post ':collection_id/edit', to: 'collection#update_buttons', as: 'update'
    end
  end

  scope 'work', as: 'work' do
    get 'delete', to: 'work#delete'
    get 'update_featured_page', to: 'work#update_featured_page'
    get 'pages_tab', to: 'work#pages_tab'
    get 'edit', to: 'work#edit'
    get 'revert', to: 'work#revert'
    post 'update', to: 'work#update'
    post 'create', to: 'work#create'
    patch 'update_work', to: 'work#update_work'
  end

  scope 'page', as: 'page' do
    get 'new', to: 'page#new'
    get 'delete', to: 'page#delete'
    get 'reorder_page', to: 'page#reorder_page'
    get 'edit', to: 'page#edit'
    get 'rotate', to: 'page#rotate'
    post 'update', to: 'page#update'
    post 'create', to: 'page#create'
  end

  scope 'article', as: 'article' do
    get 'list', to: 'article#list'
    get 'tooltip', to: 'article#tooltip'
    get 'delete', to: 'article#delete'
    get 'show', to: 'article#show'
    post 'combine_duplicate', to: 'article#combine_duplicate'
    post 'article_category', to: 'article#article_category'
  end

  scope 'export', as: 'export' do
    get '/', to: 'export#index'
    get 'export_work', to: 'export#export_work'
    get 'export_all_works', to: 'export#export_all_works'
    post ':collection_id/:work_id/printable', to: 'export#printable', as: 'printable'
    get 'show', to: 'export#show'
    get ':work_id/tei', to: 'export#tei', as: 'tei'
    get 'subject_csv', to: 'export#subject_index_csv'
    get 'subject_details_csv', to: 'export#subject_details_csv'
    get 'subject_coocurrence_csv', to: 'export#subject_coocurrence_csv'
    get 'table_csv', to: 'export#table_csv'
    get 'export_all_tables', to: 'export#export_all_tables'
    get ':collection_id/work_metadata_csv', to: 'export#work_metadata_csv', as: 'work_metadata'
    get 'edit_contentdm_credentials', to: 'export#edit_contentdm_credentials'
    post 'update_contentdm_credentials', to: 'export#update_contentdm_credentials'
    get 'work_plaintext_verbatim', to: 'export#work_plaintext_verbatim'
  end

  scope 'bulk_export', as: 'bulk_export' do
    get ':collection_id/new', to: 'bulk_export#new', as: 'new'
    post ':collection_id/new', to: 'bulk_export#create', as: 'create'
    post ':collection_id/work_create', to: 'bulk_export#create_for_work', as: 'create_for_work'
    get '/', to: 'bulk_export#index', as: 'index'
    get ':bulk_export_id', to: 'bulk_export#show', as: 'show'
    get ':bulk_export_id/download', to: 'bulk_export#download', as: 'download'
  end

  scope 'ia', as: 'ia' do
    get 'import_work', to: 'ia#import_work'
    get 'book_form', to: 'ia#ia_book_form'
    get 'manage', to: 'ia#manage'
    get 'mark_beginning', to: 'ia#mark_beginning'
    get 'mark_end', to: 'ia#mark_end'
    get 'title_from_ocr_top', to: 'ia#title_from_ocr_top'
    get 'title_from_ocr_bottom', to: 'ia#title_from_ocr_bottom'
    post 'convert', to: 'ia#convert'
    post 'import_work', to: 'ia#import_work'
    match 'confirm_import', to: 'ia#confirm_import', via: %i[get post]
  end

  scope 'dashboard', as: 'dashboard' do
    get '/' => 'dashboard#index'
    get 'owner' => 'dashboard#owner'
    get 'watchlist' => 'dashboard#watchlist'
    get 'startproject', to: 'dashboard#startproject'
    get 'summary', to: 'dashboard#summary'
    get 'exports', to: 'dashboard#exports'
    get 'collaborator_time_export', to: 'dashboard#collaborator_time_export'
    post 'new_upload', to: 'dashboard#new_upload'
    post 'create_work', to: 'dashboard#create_work'
  end

  scope 'category', as: 'category' do
    get 'edit', to: 'category#edit'
    get 'add_new', to: 'category#add_new'
    get 'enable_gis', to: 'category#enable_gis'
    get 'disable_gis', to: 'category#disable_gis'
    get 'delete', to: 'category#delete'
    post 'create', to: 'category#create'
    patch 'update', to: 'category#update'
  end

  scope 'transcribe', as: 'transcribe' do
    get 'mark_page_blank', to: 'transcribe#mark_page_blank'
    get 'display_page', to: 'transcribe#display_page'
    get 'assign_categories', to: 'transcribe#assign_categories'
    get 'guest', to: 'transcribe#guest'
    get 'edit_fields', to: 'transcribe#edit_fields'

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :remove_col_id, :only => [:profile, :update_profile]
  # no layout if xhr request
  layout Proc.new { |controller| controller.request.xhr? ? false : nil }, :only => [:update, :update_profile, :api_key]

  PAGES_PER_SCREEN = 50

  def demo
    session[:demo_mode] = true;
    redirect_to dashboard_path
  end

  def feature_toggle
    feature = params[:feature]
    value = params[:value]
    session[:features] ||= {}
    if value=='enable'
      session[:features][feature]=true
    elsif value=='disable'
      session[:features][feature]=nil
    else
      if session[:features][feature]
        render :plain => "#{feature} is enabled"
      else
        render :plain => "#{feature} is disabled"
      end
      return
    end
    redirect_back :fallback_location => dashboard_role_path
  end

  def choose_locale
    new_locale = params[:chosen_locale].to_sym
    if !I18n.available_locales.include?(new_locale)
      # use the default if the above optiosn didn't work
      new_locale = I18n.default_locale
    end

    if user_signed_in?
      current_user.preferred_locale = new_locale
      current_user.save
    else
      session[:current_locale] = new_locale
    end
    redirect_back :fallback_location => dashboard_role_path
  end


  NOTOWNER = "NOTOWNER"
  def update
    # spam check
    if !@user.owner && (params[:user][:about] != NOTOWNER || params[:user][:about] != NOTOWNER)
      logger.error("Possible spam: deleting user #{@user.email}")
      @user.destroy!
      redirect_to dashboard_path
    else
      params_hash = user_params.except(:notifications)
      notifications_hash = user_params[:notifications]
      params_hash.delete_if { |k,v| v == NOTOWNER }
      params_hash[:dictation_language] = params[:dialect]

      if params_hash[:slug] == ""
        @user.update(params_hash.except(:slug))
        login = @user.login.parameterize
        @user.update(slug: login)
      else
        @user.update(params_hash)
      end
        @user.notification.update(notifications_hash)

      if @user.save!
        flash[:notice] = t('.user_updated')
        ajax_redirect_to({ :action => 'profile', :user_id => @user.slug, :anchor => '' })
      else
        render :action => 'update_profile'
      end
    end
  end

  def update_profile
    unless @user
      @user = User.friendly.find(params[:user_slug])
    end

    if @user.real_name.blank?
      @user.real_name = @user.display_name || @user.login
    end

    # Set dictation language to default (en-US) if it doesn't exist
    lang = !@user.dictation_language.blank? ? @user.dictation_language : "en-US"
    # Find the language portion of the language/dialect or set to nil
    part = lang.split('-').first
    # Find the index of the language in the array (transform to integer)
    @lang_index = Collection::LANGUAGE_ARRAY.size.times
      .select {|i| Collection::LANGUAGE_ARRAY[i].include?(part)}[0]
    # Then find the index of the nested dialect within the language array
    int = Collection::LANGUAGE_ARRAY[@lang_index].size.times
      .select {|i| Collection::LANGUAGE_ARRAY[@lang_index][i].include?(lang)}[0]
    # Transform to integer and subtract 2 because of how the array is nested
    @dialect_index = !int.nil? ? int-2 : nil
  end


  def api_key
    @user = current_user
  end

  def generate_api_key
    @user = current_user
    @user.api_key = User.generate_api_key
    @user.save!

#    ajax_redirect_to(user_api_key_path(@user))
    render :action => :api_key, :layout => false
  end

  def disable_api_key
    @user = current_user
    @user.api_key = nil
    @user.save!
    # ajax_redirect_to(user_api_key_path(@user))
    render :action => :api_key, :layout => false
  end

  def profile
    #find the user if it isn't already set
    unless @user
      @user = User.friendly.find(params[:id])
    end
    if !@user.deleted || current_user.admin
      @collections_and_document_sets = @user.visible_collections_and_document_sets(current_user)
      @collection_ids = @collections_and_document_sets.map {|collection| collection.id}
      @deeds = @user.deeds.includes(:note, :page, :user, :work, :collection).order('created_at DESC').paginate :page => params[:page], :per_page => PAGES_PER_SCREEN
    else
      flash[:notice] = t('.user_deleted')
      redirect_to dashboard_path
    end
    if @user.owner?
      collections = @user.all_owner_collections.carousel
      sets = @user.document_sets.carousel
      @carousel_collections = (collections + sets).sample(8)
    end
  end

  private

  def user_params
    params.require(:user).permit(:picture, :real_name, :orcid, :slug, :website, :location, :about, :preferred_locale, notifications: [:user_activity, :owner_stats, :add_as_collaborator, :add_as_owner, :note_added, :add_as_reviewer])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
#  protect_from_forgery with: :exception, except: [:saml]
#  skip_before_action :verify_authenticity_token
  skip_forgery_protection
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end


  def saml
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "SAML") if is_navigational_format?
    else
      session["devise.saml_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    flash[:error] = t('authentication_failed')
    redirect_to new_user_registration_url
  end
end

app/views/user/_owner_profile.html.slim
-user_name = user.display_name.presence || user.login
section.user-profile
  .user-profile_image
    =profile_picture(@user, 128)
  .user-profile_details
    .headline
      h1.headline_title
        =user_name
      -if user == current_user
        .headline_aside
          =link_to(update_profile_path(user.id), class: 'button outline', :data => { litebox: { hash: 'update-profile' }})
            =svg_symbol '#icon-edit', class: 'icon'
            span =t('.edit_profile')
          |&nbsp;&nbsp;
          =link_to(edit_user_registration_path, class: 'button outline')
            =svg_symbol '#icon-user', class: 'icon'
            span =t('.login_and_password').html_safe
          |&nbsp;&nbsp;
          =link_to(user_api_key_path, class: 'button outline', :data => { litebox: { hash: 'api-key' }})
            =svg_symbol '#icon-lock', class: 'icon'
            span =t('.api_keys').html_safe
    .user-profile_stats
      -if user.website.present?
        =link_to t('.website'), user.website, target: '_blank', rel: 'nofollow'
      -if user.about.present?
        div ==user.about

-unless carousel_collections.blank?
  .carousel
    -carousel_collections.each do |c|
      -snippet = to_snippet(c.intro_block)
      .carousel_slide
        =link_to image_tag(c.picture_url, alt: c.title), collection_path(c.owner, c), class: 'carousel_slide_image'
        .carousel_slide_content
          h3 =link_to c.title, collection_path(c.owner, c)
          p =snippet

.columns
  article.maincol
    -if @collections_and_document_sets.any?{ |c| c.class == Collection && c.supports_document_sets }
      =render partial: '/dashboard/hierarchical_collections_and_document_sets', collection: @collections_and_document_sets, as: :cds
    -else
      =render partial: '/dashboard/alphabetical_collections_and_document_sets', collection: @collections_and_document_sets, as: :cds
  aside.sidecol

-content_for :javascript
  javascript:
    $(function(){
      $('.carousel').slick({
        autoplay: true,
        arrows: true,
        infinite: true,
        speed: 1000,
        autoplaySpeed: 8000,
        prevArrow: '<button class="button outline" aria-label="#{t('.previous_image')}">#{svg_symbol '#icon-arrow-left', class: 'icon'}</button>',
        nextArrow: '<button class="button outline" aria-label="#{t('.next_image')}">#{svg_symbol '#icon-arrow-right', class: 'icon'}</button>',
      });
    });

app/views/user/api_key.html.slim
.litebox-embed(style="width:550px")
  h1= t('.api_key')

  p== t('.api_key_description')

  -if @user.api_key.blank?
    p= t('.no_api_key_description')

    =button_to(t('.generate_key'), user_generate_api_key_path(@user))

  -else
    p= t('.your_api_key_description')
      
    code =@user.api_key

    p =button_to(t('.delete_key'), user_disable_api_key_path(@user))

app/views/user/profile.html.slim
-user_name = @user.display_name.presence || @user.login
-content_for :page_title, user_name
-content_for :meta_description, t('.users_profile_at_fromthepage', user: user_name, about: @user.about)
-if @user.owner?
  =render partial: 'owner_profile', locals: { user: @user, carousel_collections: @carousel_collections, collections_and_document_sets: @collections_and_document_sets }
-else
  section.user-profile
    .user-profile_image
      =profile_picture(@user)
    .user-profile_details
      .headline
        h1.headline_title
          =user_name
        -if @user == current_user
          .headline_aside
            =link_to(user_update_profile_path(:user_id => @user.id), class: 'button outline', :data => { litebox: { hash: 'update-profile' }})
              =svg_symbol '#icon-edit', class: 'icon'
              span =t('.edit_profile')
            |&nbsp;&nbsp;
            =link_to(edit_user_registration_path, class: 'button outline')
              =svg_symbol '#icon-user', class: 'icon'
              span =t('.login_and_password').html_safe
      .user-profile_stats
        span ="#{number_with_delimiter(@user.deeds.count)} #{t('.contribution', count: @user.deeds.count)}"
        span = t('.user_since', date: l(@user.created_at.to_date))
        -if @user.last_sign_in_at.present?
          span = t('.last_seen', date: l(@user.last_sign_in_at.to_date))

  

  h2 =t('.recent_activity_by', user_display_name: @user.display_name)
  table.datagrid.striped
    -@deeds.each do |d|
      tr
        td.w100.toleft
          -if d.work.nil? || d.work.access_object(current_user)
            =render(:partial => 'deed/deed.html', :locals => { :deed => d, :long_view => true })
          -else
            =raw(strip_tags(render(:partial => 'deed/deed.html', :locals => { :deed => d, :long_view => true })))
            
        td
          small.label(class="deed-type-#{d.deed_type}") =t(d.deed_type_name)
        td.nowrap
          =time_tag(d.created_at, class: 'small fglight')
            =t('time_ago_in_words', time: time_ago_in_words(d.created_at))

  br
  small.legend
    =will_paginate @deeds, { :class => 'deed-pager', :page_links => false, :previous_label => t('.newer_activity'), :next_label => t('.older_activity') }

app/views/user/update_profile.html.slim
.litebox-embed(style="width:570px")
  h1 =t('.update_user_profile')
  -if @user.owner
    p =t('.name_only_required')
      =form_for :collection, url: collection_update_path(@collection), html: { multipart: true, class: 'image-form' } do |f|
        =hidden_field_tag(:collection_id, @collection.id)
        label(data-empty=t('.no_image') data-hover=t('.upload_image') aria-label=t('.upload_image') title=t('.upload_image'))
          =f.file_field :picture, accept: 'image/*'
          -if @collection.picture_url(:thumb)
            =image_tag(@collection.picture_url(:thumb), alt: @collection.title)
      p.fglight =t('.picture_to_be_used_message')

  =form_for(@user, { :url => { :action => 'update' }}) do |f|
    =hidden_field_tag :user_id, @user.id
    =validation_summary @user.errors
    table.form
      tr.big
        th =f.label :real_name, t('.name')
        td.w100 =f.text_field :real_name
      tr
        th =f.label :orcid, t('.ocrid_id')
        td =f.text_field :orcid, :placeholder => t('.your_ocrid_id')
      -if @user.owner
        tr
          th =f.label :picture, t('.picture')
          td 
            =f.file_field :picture, accept: 'image/*'
            -if @user.picture_url(:thumb)
              .userpic =image_tag(@user.picture_url(:thumb), alt: @user.display_name)
        tr
          th= t('.user_url')
          td www.#{Rails.application.routes.default_url_options[:host]}/#{@user.slug}
        tr
          th= t('.sign_up_url')
          td www.#{Rails.application.routes.default_url_options[:host]}/#{@user.slug}/sign_up
        tr
          th =f.label :slug, t('.url')
          td =f.text_field :slug, value: @user.slug
        tr
          th =f.label :website, t('.website')
          td =f.text_field :website, :placeholder => t('.your_blog_or_homepage')
        tr
          th =f.label :location, t('.location')
          td =f.text_field :location, :placeholder => t('.where_are_you_from')
        tr
          td(colspan="2")
            =f.label :about, t('.about_you'), class: 'above'
            =f.text_area :about, rows: 4
      -else
        =f.hidden_field :website, value: "NOTOWNER"
        =f.hidden_field :about, value: "NOTOWNER"
      tr  
        th =f.label :preferred_locale, t('.interface_language'), class: 'collection-label'
        td =f.select :preferred_locale, options_for_select(@dropdown_locales.map{|code| [I18n.translate(code), code]}, @user.preferred_locale), :include_blank => true
      tr  
        td(colspan="2")
          =label_tag :dictation_language, t('.default_dictation_language'), class: 'collection-label'
      tr  
        td(colspan="2")
          =select_tag :dictation_language, {}, {onchange:'updateCountry()', class: 'w30'}
          |&nbsp;
          =select_tag :dialect, {}, {class: 'w40'}

    p.email_notifications =t('.select_notification')
    table.form.email_notifications
      tr
        td =f.check_box("notifications[user_activity]", {checked: @user.notification.user_activity})
        th =f.label :user_activity, t('.user_activity')
      -if @user.owner
        tr
          td =f.check_box("notifications[owner_stats]", {checked: @user.notification.owner_stats})
          th =f.label :owner_stats, t('.owner_stats')
      tr
        td =f.check_box("notifications[add_as_collaborator]", {checked: @user.notification.add_as_collaborator})
        th =f.label :add_as_collaborator, t('.add_as_collaborator')
      tr
        td =f.check_box("notifications[add_as_reviewer]", {checked: @user.notification.add_as_reviewer})
        th =f.label :add_as_reviewer, t('.add_as_reviewer')
      tr
        td =f.check_box("notifications[add_as_owner]", {checked: @user.notification.add_as_owner})
        th =f.label :add_as_owner, t('.add_as_owner')
      tr
        td =f.check_box("notifications[note_added]", {checked: @user.notification.note_added})
        th =f.label :page_edited, t('.page_edited')

    .toolbar
      .toolbar_group.aright =f.button t('.update_profile')

javascript:
  $(function(){
    var initialLang = "#{@lang_index}";
    var initialDialect = "#{@dialect_index}";
    
    console.log("Init Lang: ", initialLang, " Initial Dialect: ", initialDialect)
    
    for (var i = 0; i < langs.length; i++) {
      dictation_language.options[i] = new Option(langs[i][0], i);
    }
    
    findDefault(initialLang, initialDialect);
  });